services:
  - type: web
    name: flex-living-reviews-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: https://your-vercel-app.vercel.app
      - key: HOSTAWAY_API_KEY
        value: f94377ebbbb479490bb3ec364649168dc443dda2e4830facaf5de2e74ccc9152
      - key: HOSTAWAY_ACCOUNT_ID
        value: 61148
      - key: HOSTAWAY_BASE_URL
        value: https://api.hostaway.com/v1
      - key: GOOGLE_PLACES_API_KEY
        value: your_google_api_key_here
